
- обработка ошибок в стиле C
- try/catch/throw
- исключения в конструкторах и деструкторах
- идиома RAII: использование и примеры классов
- гарантии исключений


# Обработка ошибок в стиле C

Информация об ошибке: через возвращаемое значение и глобальную переменную:
```cpp
FILE* fopen(...); {
	if (file not found) {
		errno = 666;
		return NULL;
	}
	if (permission denied) {
		errno 777;
		return NULL;
	}
	...
}
```

Проблемы:
* Мало информации. Не знаем причину: нет файла, нет права доступа; ...
* Не всегда хватает диапазона возвращаемых значений функции.
* Код логики и обработка ошибок перемешаны.

# C++-style

Методы throw-catch обработки ошибок.

```cpp
class MyException {
private:
	char message[256];
public:
	const char* get();
};

double divide(int a, int b) {
	if (b == 0) {
		throw MyException("Devision by zero!");
	}
	return a/b;
}

int main() {
	try {
		x = divise(c, d);
	} catch(MyException &e) {
		std::cout << e.get(); // 1. tell user
		// 2. delete []..; free resource
		// 3. throw e; inform caller func
	}
	return 0;
}
```


# Исключения в конструкторах и деструкторах

Если в конструкторе бросается исключение, то объект получается "недостроенным". Деструктор у недостроенных объектов не вызывается. Поэтому надо предусмотреть такой исход и освободить выделенную память самостоятельно.

```cpp
class PhoneBookItem {
	PhoneBookItem(const char* audio, const char* picture) {
		try {
			af = fopen(audio, "r");
			pf = fopen(pic, "r");
			divide(c, e) // could throw exception
			f();
		} catch(MyException &e) {
			fclose(af);
			fclose(pf);
			throw e;
		}
	}
	~PhoneBookItem() {
		fclose(af);
		fclose(pf);
	}
};
```

Исключения в деструкторах бросать запрещено. Если это происходит, программа должна закрываться аварийно.

# Идиома RAII: использование и примеры классов

**RAII** - Resource Acquisition Is Initialization.
Взятие ресурса нужно "инкапсулировать" в класс, чтобы в стучае исключения вызвался деструктор и освободил ресурс.

```cpp
f() {
	MyArray buffer(n);
	if (...) throw MyExcpetion(...);
}
```

```cpp
g() {
	unique_ptr p (new Person("Jenya ", 36, true)); // or another smart ptr
	divide(c , e); // could throw exception
}
```

# Гарантии исключений

Гарантии:
* Обязательства функции (метода) с точки зрения работы с исключениями;
* Документация для программиста, работающего с функцией (методом).

Виды гарантий:
1. `no throw guarantee` - не бросает исключений вообще;
2. `basic guarantee` - в случает возникновения исключения ресурсы не утекают;
3. `strong guarantee` - переменные принимают те же значения, что и до возникновения ошибки
---
1. `no throw`:

```cpp
void strlen( const char * s ) {
	int count = 0;
	while (* s != 0) {
		s ++; count ++;
	}
	return count;
}

void f() {
	try {
		strlen(...);
		divide(a , b );
	} catch (...) { //catch everything
	}
}
```

2. `basic guarantee`:
Если произойдет исключение, то память "течь" не будет, но измененные элементы array свои значения не восстановят. 
```cpp
class PersonDatabase {
	MyVector<Person> array;
	void process() {
		unique_ptr<Person> p (new Person(...));
		for (int i = 0; i < array.length; i ++) {
			int a = divide(rand(), rand() ; // could throw exception
			array[i]->setAge(a);
			std::cout << p;
		}
	}
};
```

3. `strong guarantee`:
Идиома: copy-and-swap
```cpp
class PersonDatabase {
	MyVector<Person>array;
	void process() {
		unique_ptr<Person> p(new Person(...));
		MyVector<Person> copy(array);
		for (int i = 0; i < array.length; i ++) {
			int a = divide(rand(), rand()); // could throw exception
			copy[i]->setAge(a);
		}
		array.swap(copy);
	}
};
```
